export enum STORAGE_KEYS {
    USER_NAME = "USER_NAME",
    USER_GROUP = "USER_GROUP",
    USER_ID = "USER_ID",
    USERS = "USERS",
    ROOM_SELECT = "ROOM_SELECT",
    TEAM_CODE = "TEAM_CODE",
    TURN = "TURN",
    MY_SCORE = "MY_SCORE",
    RED_GROUP_SCORE = "RED_GROUP_SCORE",
    BLUE_GROUP_SCORE = "BLUE_GROUP_SCORE",
    GREEN_GROUP_SCORE = "GREEN_GROUP_SCORE",
}
